FROM openjdk:11
LABEL maintainer="nayansengupta99@gmail.com"
EXPOSE 8081
ADD target/Cart-Service-0.0.1-SNAPSHOT.jar Cart-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Cart-Service-0.0.1-SNAPSHOT.jar"]